# The URL the site will be built for
theme = "linkita"
base_url = "https://theora59-dev.github.io/blog/"
title = "Theora59 Devs Adventures"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feeds = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags", feed = true },
    { name = "categories", feed = true, paginate_by = 5 },
]

[markdown]
render_emoji = false
smart_punctuation = false

[markdown.highlighting]
style = "inline"
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
# Put all your custom variables here
description = "Blog d'un étudiant en info passionné par Rust, l'embarqué, le pentest et moultes autres technologies"
author = "Theora59-dev"
github = "https://github.com/theora59-dev"
show_socials = false

close_responsive_menu_on_resize = true
copy_button = true
layout = "full"
show_default_author = false
header_menu_name = "main_menu"

[extra.menus]
# Définir le menu "main_menu" (le nom doit correspondre à header_menu_name)
main_menu = [
    { url = "/", name = "Accueil", trailing_slash = true },
    { url = "/projets/", name = "Projets", trailing_slash = true },
    { url = "/cours/", name = "Cours", trailing_slash = true },
    { url = "/tags/", name = "Tags", trailing_slash = true },
    { url = "https://github.com/Theora59-dev/", name = "Github", new_tab = true },
]
